version: '3.8'

services:

  db:
    image: "postgres"
    container_name: db-shop
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "shop"
    volumes:
      - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/val/lib/postgresql/data


volumes:
  db-data:
networks:
  msanet:
    driver: bridge