server:
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: online-store-showcase
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://db:5432/shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public
    enabled: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types.print.banner: false
    open-in-view: false

